sudo: required

language: minimal

services:
  - docker

env:
  - POSTGRES_IMAGE=bitnami/postgresql:12.2.0 CLAIR_VERSION=v2.1.0 CLAIR_LOCAL_SCAN_IMAGE=arminc/clair-local-scan PUSH_CLAIR_LOCAL_SCAN_IMAGE=csturiale/clair-local-scan

install:
  - docker build -t $CLAIR_LOCAL_SCAN_IMAGE --build-arg VERSION=$CLAIR_VERSION clair

before_script:
  - docker pull $POSTGRES_IMAGE
  - docker run -d --name postgres -e POSTGRES_PASSWORD=password $POSTGRES_IMAGE
  - until docker run --rm -it --link postgres:postgres -e PGPASSWORD=password $POSTGRES_IMAGE pg_isready -U postgres -h postgres; do sleep 1; done
  - docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE

script:
  - ./check.sh

after_success:
  - docker stop clair
  - docker stop postgres
  - docker commit postgres arminc/clair-db:$(date +%Y-%m-%d)
  - docker tag arminc/clair-db:$(date +%Y-%m-%d) csturiale/clair-db:latest
  - docker tag $CLAIR_LOCAL_SCAN_IMAGE ${PUSH_CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${TRAVIS_COMMIT}
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  on:
    branch: master
  script:
    docker push ${PUSH_CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${TRAVIS_COMMIT} &&
    docker push $PUSH_CLAIR_LOCAL_SCAN_IMAGE:latest && 
    docker push csturiale/clair-db:$(date +%Y-%m-%d) &&
    docker push csturiale/clair-db:latest
